"""Change user_id to integer

Revision ID: cc314b1f837a
Revises: adb43f05b61c
Create Date: 2024-01-09 22:47:45.692552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc314b1f837a'
down_revision: Union[str, None] = 'adb43f05b61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE user_model ALTER COLUMN user_id TYPE INTEGER USING user_id::integer")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.execute("ALTER TABLE user_model ALTER COLUMN user_id TYPE VARCHAR(255) USING user_id::varchar")
    # ### end Alembic commands ###
