"""New Migration

Revision ID: ccc0a806606b
Revises: 5904d0790d67
Create Date: 2024-01-04 22:42:30.602390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc0a806606b'
down_revision: Union[str, None] = '5904d0790d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_model', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'expense_model', 'user_model', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense_model', type_='foreignkey')
    op.drop_column('expense_model', 'username')
    # ### end Alembic commands ###
